### ISSUE TITLE
Failed to install.. Wrong size for extra data

### ISSUE THREAD

**Issue by Mic1e** [flathub/io.designer.GravitDesigner#35] opened 2021-06-14 23:45 UTC
Hello, I can't seem to be able to install Gravit Designer on Mabox, kernel 5.12.9-1-MANJARO.
I get the following error:
```
Looking for matches…

io.designer.GravitDesigner permissions:
    ipc    network    x11    dri    file access [1]   tags [2]

    [1] home
    [2] proprietary


        ID                                   Branch          Op          Remote           Download
 1. [✗] io.designer.GravitDesigner           stable          i           flathub          418.8 MB / 420.6 MB

Error: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
error: Failed to install io.designer.GravitDesigner: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
```
Thanks in advance for any help!

**Comment by FakeShemp** [comment] 2021-06-15 10:31
Duplicate of #2

**Closed by FakeShemp** 2021-06-15 10:31 UTC
