### ISSUE TITLE
not able to run GravitDesigner

### ISSUE THREAD

**Issue by hyphone** [flathub/io.designer.GravitDesigner#1] opened 2018-08-29 17:31 UTC
Hello and good day,

sadly I'm unable to run GravitDesigner through flatpak. That's the output:

`$ flatpak run io.designer.GravitDesigner`

`/app/bin/gravit-designer: Line 2: /app/extra/gravit-designer/gravit-designer: permission denied`
`/app/bin/gravit-designer: Line 2: exec: /app/extra/gravit-designer/gravit-designer: unable to execute: permission denied`

Edit:
Ubuntu 18.04
flatpak 1.0.0
installed GravitDesigner systemwide via `sudo flatpak flathub install io.designer.GravitDesigner`

**Comment by alex285** [comment] 2018-08-29 18:11
Same here
Flatpak 1.0.0

**Comment by nedrichards** [comment] 2018-08-29 18:26
I can reproduce this too, the flathub built version has the extraction done with a user id of 0 as opposed to your user ID when built manually.

```
nick@endless-nedr:/app/extra$ ls -lah
total 12K
drwxr-xr-x 3 0 0 4.0K Aug 29 19:15 .
drwxr-xr-x 7 0 0 4.0K Aug 29 19:15 ..
drwx------ 5 0 0 4.0K Aug 29 19:15 gravit-designer
```

vs
```
nick@endless-nedr:/app/extra$ ls -lah
total 12K
drwxr-xr-x 3 nick nick 4.0K Aug 29 19:21 .
drwxr-xr-x 7 nick nick 4.0K Aug 29 19:21 ..
drwx------ 5 nick nick 4.0K Aug 29 19:21 gravit-designer
```

**Comment by barthalion** [comment] 2018-08-29 18:58
For what it's worth, it doesn't work for me in user installation either but for different reason. A splash screen displays and then it prints useless stacktrace due to lack of debug symbols.

**Comment by barthalion** [comment] 2018-08-29 19:10
Also the chmod commit I pushed is useless so feel encouraged to revert it when pushing actual fix…

**Comment by nedrichards** [comment] 2018-08-29 19:52
Fixed by https://github.com/flathub/io.designer.GravitDesigner/commit/20ea063816468dba6a87cf02055145f33ac0a574

**Closed by nedrichards** 2018-08-29 19:52 UTC
